### ISSUE TITLE
Program Listing at Home Page

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#1]
This is how we list all the programs so far:

http://codingmindsacademy.com/index.html#summercamp

I think we can keep the current style. However, we might need to think about how to filter/search these once we get more programs. 

For example, we have 6 programs in Fall 2017, but we might still want to show the old Summer 2017. Or we will publish the one for Winter 2018 and after. 

I remember that the template has something like this. Could you look into this and let me know our options?

**Comment by sunyu912** [comment]
Or if it looks really good by listing all of them, we can simply just do that. I don't know.

**Comment by japantaleon** [comment]
Yup, the template has a category button we can implemented. It's a little bulky, I'll look into making it prettier. Though, to be creative, making the header the drop menu button would be cool too. I'll update you on this later.

**Comment by japantaleon** [comment]
Took a bit, but here is a demo, link below on a category button added.
http://codingmindsacademy.com/Filteradded.html

I'll continue to integrated and  see if I can make a better design, unless how the current demo is fine?

**Comment by sunyu912** [comment]
Does it have any explicit options rather than clicking on the dropdown
menu?

**Comment by japantaleon** [comment]
Like can it display more information ? little elaboration might help :)

**Comment by sunyu912** [comment]
Let's try to add 3 filters:

1) Age Group (ele, middle, high school)
2) Topic Category (Robotics, Game, Mobile, etc.)
3) Location (Irvine, Rancho Cucumaga, etc.)

**Comment by japantaleon** [comment]
Added Multiple Categories doesn't work properly. More than one doubles the data displayed in the drop down. 

http://codingmindsacademy.com/Filteradded.html

**Comment by sunyu912** [comment]
So this won't work, right?

**Comment by japantaleon** [comment]
No it won't, it requires more in-depth Javascript to get something similar. But under the current template we can't.

**Comment by sunyu912** [comment]
Alright. Could you clean it up to have just one filter - but make sure the
shape looks right in mobile.

For the dummy category, let's use the grade level, such as elementary,
middle, high schools.

**Comment by japantaleon** [comment]
Mobile, Dummy data & Single Filter *
http://codingmindsacademy.com/Filteradded.html

**Comment by sunyu912** [comment]
Double check the Filter click behavior from the template - it does not go away after clicking.

<img width="712" alt="screen shot 2017-11-29 at 12 16 15 pm" src="https://user-images.githubusercontent.com/1639351/33397013-31f864f4-d4ff-11e7-9805-377d88c01ddb.png">
