### ISSUE TITLE
Site Description needs to be changed

### ISSUE THREAD

**Issue by anthonygraca** [CodingMindsAcademy/CodingMindsAcademy.github.io#14]
![screenshot](https://user-images.githubusercontent.com/4534967/34016906-6e402462-e0d8-11e7-81b6-f49580b8f63b.png)

When the link is shared, the description of the site says "Site Description Here"

**Comment by sunyu912** [comment]
Great catch! Thanks so much Anthony!

**Comment by cassilam** [comment]
I updated the site description. Let me know if you want to change it to something else

**Comment by sunyu912** [comment]
Thanks Cassi! This is great.

Could you help to check all the other pages such as contact-us, why-coding, etc., for both Chinese and English? I guess most of those pages do not have a description. You can simply use your own words to form a sentence and put it there. This field is important for website SEO.

**Comment by cassilam** [comment]
I updated the descriptions for all the pages.

**Comment by sunyu912** [comment]
Awesome!
