### ISSUE TITLE
Get Familiar with the new Course Details Page Template

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#15]
Hi Cassi,

I have done cleaned up the course details page and added a cool feature - update the course details page using JSON file. I would like you to take a look at what I have done, and then you might be able to help with the page update.

I used AngularJS to do this, which you definitely should learn. https://angularjs.org/ I am using AngularJS 1.6, so you might want to start learning AnguarJS from 1.6.

To get started, I would suggest the following steps:

1) Sync up the code base of this rep. I have done quite a lot of updates.

2) Please focus on the template page: `course-layout-version-3.html` and its associated JavaScript file `course-control/v3.js` . These two files use AngularJS to enable loading the content from the JSON config. It's the basic feature of AngularJS. Take a look at that and see if it makes sense.

3) You can also take a look at `course-layout-version-3-cn.html` and its associated `course-control/v3-cn.js` . These are exactly the same as the other two, but for Chinese version.

4) If you can understand these files. Please try to create a new course by yourself. For example, I want to create a new java101 course. All you need to do is to copy `course-layout-version-3.html` to a new file `java101.html`, and copy `v3.js` to `java101.js`. Then, you just need to update all the fields in `java101.js`, followed by update 3 things in the `java101.html` file. Please see my comments in the top of the `course-layout-version-3.html`. 

5) Try to load the new course `java101.html` and see if that works. If so, please also try to add the Chinese version, which means you need to create `java101c.html` and `java101c.js`

Please let me know if you have any questions. If you can understand this, I will have some tasks for you to try. 

Thanks,

Yu

**Comment by cassilam** [comment]
Is course-control/v3.js missing the description needed for template 2?

**Comment by sunyu912** [comment]
Great job Cassi!
