### ISSUE TITLE
Change Title and Description Back to Hard Coded Text

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#16]
Hi Cassi,

The reason we do not want to use {{courseTitle}} and {{courseDescription}} is that sometimes certain system will try to load the title and description in a preview mode, and the JS based content cannot be rendered correctly. For instance, if you paste your java101.html link in the Outlook Email, you will see something like below:

<img width="820" alt="screen shot 2017-12-20 at 9 30 43 pm" src="https://user-images.githubusercontent.com/1639351/34241871-4a10665c-e5cd-11e7-83b6-4034a4e75d1d.png">

If I hard code it, it will be:

<img width="822" alt="screen shot 2017-12-20 at 9 31 04 pm" src="https://user-images.githubusercontent.com/1639351/34241886-5349d78a-e5cd-11e7-97a4-9df5ff53dd82.png">

Could you help to change the two template html files back to hard coded one?

Thanks,

Yu

**Comment by cassilam** [comment]
Changed the two files back to hard coded ones.
