### ISSUE TITLE
Change the Old 3 Courses to the New Template 

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#17]
Let's change the following 3 courses into the new template. Please do not delete the old files. Simply use the new template approach to create 3 sets of new files. We only need to fill in the new template based on the content from the old ones.

1. SPRK
http://codingmindsacademy.com/page-class-sprk.html
http://codingmindsacademy.com/sprk-cn.html

=>

sprk.html / sprk.js
sprkc.html / sprkc.js

2. App Inventor
http://codingmindsacademy.com/page-class-mobile.html
http://codingmindsacademy.com/mobile-cn.html

=>

mobile.html / mobile.js
mobilec.html / mobilec.js

3. Python
http://codingmindsacademy.com/page-class-python.html
http://codingmindsacademy.com/python-cn.html

python.html / python.js
pythonc.html / pythonc.js

Please let me know if you don't know the content to fill in.

**Comment by cassilam** [comment]
Do I use the prices and schedules on the template or on the current course pages?

And which address do I use for the SPRK course?

**Comment by sunyu912** [comment]
Thanks Cassi. No worries about the pricing for now. I will get that
finalized later.

**Comment by cassilam** [comment]
I've changed these 3 courses to use the new template.

**Comment by sunyu912** [comment]
Looks great!
