### ISSUE TITLE
Update Course List Control for the 3 Old Courses 

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#18]
Once we get the 3 courses updated with the new files, we need to update `course-control/courselist.js` and `course-control/courselist-cn.js`

All we need is to update the `detailsUrl` and `registerUrl` fields for these 3 courses.

Make sure you understand how `courselist.js` and `courselist-cn.js` work with `index.html` and `index-cn.html`

**Comment by cassilam** [comment]
Updated the course list. Let me know if there are any issues with it

**Comment by sunyu912** [comment]
Awesome! Thanks for the quick update Cassi!
