### ISSUE TITLE
Home Screen Start

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#2]
This is what we have currently:

<img width="1291" alt="screen shot 2017-11-01 at 1 58 18 pm" src="https://user-images.githubusercontent.com/1639351/32297567-c89c016c-bf0c-11e7-9b54-899f99d66482.png">

If we still want to keep something like this - one section / one slide / simple / clean. Do you have any recommendations on the text/title/image? 

It does not mean that the current one is not good. I am just curious on if we have other options.

**Comment by japantaleon** [comment]
It looks great but if we look at options. There's a trend of adding gradients, more and more apps/web are intergrading some type of gradient. Whether be a button or background. The template has a good background class, maybe toying with that could make it more captivating ? (not that it isn't already hehehe). Hulu does a good job at this. 
![image](https://user-images.githubusercontent.com/24999862/32301086-a17a17d8-bf19-11e7-92da-c24303198d8f.png)

Will create mock-up soon!

**Comment by sunyu912** [comment]
Yes, let's see some samples. As long as it fits the color theme of the logo, it should be fine. White is also good because it's clean and simple.
