### ISSUE TITLE
English Version of the Scratch Course

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#20]
Hi Cassi,

I have just pushed the Chinese version for Scratch: https://codingmindsacademy.com/scratchc.html

I am wondering if you are able to make the English version. I have already setup all the pages. The only thing you need to do is to translate the field from this file: https://github.com/CodingMindsAcademy/CodingMindsAcademy.github.io/blob/master/course-control/scratchc.js 
to this file:
https://github.com/CodingMindsAcademy/CodingMindsAcademy.github.io/blob/master/course-control/scratch.js

And of course, only from the beginning to the "goals" section. 

Since I am not a native English speaker, my translation is sometimes not that good ;-) I forgot if you can read Chinese or not. If not, no worries about that, and I will do the translation later. 

Thanks and happy new year!

Yu

**Comment by cassilam** [comment]
I've translated the content from scratchc.js and scratchc.html into English. The only issue is I don't know how to translate 计算器编程能力 into English

**Comment by sunyu912** [comment]
Thanks Cassi. It looks great. I think you are too serious ;-) For English translation, you don't need to translate it word-by-word. In many cases, a similar meaning is fine. I would call it "programming skills" for "计算器编程能力". I have already pushed that. Thanks again!
