### ISSUE TITLE
Add Keywords Tag for All Pages

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#24]
This will be very useful for SEO. 
https://www.w3schools.com/tags/tag_meta.asp

See here for an example:
<meta name="keywords" content="HTML,CSS,XML,JavaScript">

For example, for the App Inventor Page, let's add all the related keywords:

English Version:
**App Inventor, Mobile App Development**, Kids Learning Coding, K-12 Programming, K-12 Coding, Kids Coding, After School Coding, After School Program

Chinese Version
**App Inventor, 手机开发**, 青少年编程, 课后编程辅导, 编程思维, 编程竞赛

For the Python Page, let's add:

English Version:
**Introduction to Python, Kids Python**, Kids Learning Coding, K-12 Programming, K-12 Coding, Kids Coding, After School Coding, After School Program

Chinese Version:
**Python, Python编程**, 青少年编程, 课后编程辅导, 编程思维, 编程竞赛

Of course, let's also put these into the V3 templates.

If you can think about other keywords, feel free to add those.

**Comment by cassilam** [comment]
I added keywords to all the pages

**Comment by sunyu912** [comment]
Thanks Cassi!
