### ISSUE TITLE
New App Course Translation

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#25]
Hi @cassilam  Could you help with this translation? I just pushed a new course:

https://codingmindsacademy.com/ceappc.html

Could you update the file ceapp.html based on the Chinese content. BTW, you might be able to find a lot of similar text reusable at: https://codingmindsacademy.com/apcsp.html 

Thanks a lot!

**Comment by cassilam** [comment]
Updated ceapp.html
