### ISSUE TITLE
Duplicate the Chinese Homepage (index-cn.html) for English (index.html)

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#35]
@cassilam  The Chinese page has the summer camp schedule. Could you help to put that into the English version as well? You might need to create some images for the schedule overview. Let me know if you need any help.

**Comment by sunyu912** [comment]
Here is the Keynote for the schedules. I forgot if you have a Mac. 

[Table.zip](https://github.com/CodingMindsAcademy/CodingMindsAcademy.github.io/files/1912925/Table.zip)

**Comment by cassilam** [comment]
Updated the summer camp schedule for index.html
