### ISSUE TITLE
Apply the Recent CN Homepage Changes to the English Homepage

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#36]
Please check out the major changes in these two files:

index-cn.html
course-control/courselist-cn.js

**Comment by sunyu912** [comment]
@cassilam Hi Cassi, let's try to get this done by this weekend if you are available. Thanks a lot!

**Comment by cassilam** [comment]
@sunyu912 I'll try to get this done by this weekend
