### ISSUE TITLE
New Tab for News/Blogs and the Template to Use

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#4]
We need a new tab to show news / blogs that contains the recent activities, announcement and other things. You can do some research and see what would be the best section title to put. 

<img width="1194" alt="screen shot 2017-11-01 at 2 06 10 pm" src="https://user-images.githubusercontent.com/1639351/32297891-ed702198-bf0d-11e7-9af5-e60ca5e4cba6.png">

Also, which page template we should use. I remember there are something in the template package for this purpose.

**Comment by japantaleon** [comment]
"News",  "Currently" , "What's going on?", "What's happening ?". Just some suggestions, all would work.

For displaying there is several we can use. Though the "blog-articles-magazine.html#" is by far the best! Really eye catchy and has more of a "Apple" feel.

**Comment by sunyu912** [comment]
Let's use the simple ones - News

Could you push this blog-articles-magazine sample page to the repo so that we can see it?

**Comment by japantaleon** [comment]
http://codingmindsacademy.com/blog-articles-magazine.html

Here it is

**Comment by sunyu912** [comment]
Looks good. Let's use this one.

**Comment by sunyu912** [comment]
Let's use this template. Two things to finalize:

1) Clean up this page - replacing all the page headers/footers/menus/links with the ones we used for the other pages. 

2) Also push a news details page - the page to show when we click on the news item. 

3) Let's add "News" to the top-level menu bar for ALL pages.

**Comment by japantaleon** [comment]
**1. News Page Clean**
http://codingmindsacademy.com/News.html

**2. News Detail Page Pushed and Cleaned**
http://codingmindsacademy.com/New-Display.html

**3. News Added to all _English Pages_**
Haven't added the direct link to news page. Since we want to have some content there first.

**Comment by sunyu912** [comment]
Looks great.
