### ISSUE TITLE
Course Details Page V3.0

### ISSUE THREAD

**Issue by sunyu912** [CodingMindsAcademy/CodingMindsAcademy.github.io#5]
Obviously, this is one of the most important pages for the website. Currently, I have made two version: 

V1.0:

http://codingmindsacademy.com/page-class-mobile.html
http://codingmindsacademy.com/page-class-sprk.html

pros: visual, rich content
cons: not fully mobile responsive

V2.0:
http://codingmindsacademy.com/apcs.html
http://codingmindsacademy.com/apcsp.html

pros: mobile responsive
cons: less visual, less info such as location

They both have advantages and disadvantages, so let's combine them into a new version V3.0.

**Comment by japantaleon** [comment]
I am pretty confident I'll be able to make V.1 responsive like V.2. I will continue to look at the CSS and see how much of V1 ill be able to keep and still have the UI look neat.

**Comment by sunyu912** [comment]
Any updates on this?

**Comment by japantaleon** [comment]
Yee, I'll upload it around 4:00 when I'm out of class.

**Comment by japantaleon** [comment]
http://codingmindsacademy.com/course-layout-version-3.html

Here it is, only comment is that for the "About AP course" theres a lot of text, I think we should change the layout on how it's been display ? Just a suggestion.

Once you see the V3, youll see that I changed the instructor part. If they click button, your profile section should look like this. This way the page keeps looking aesthetic like apple.

<img width="1440" alt="screen shot 2017-11-20 at 1 19 04 pm" src="https://user-images.githubusercontent.com/24999862/33044866-7d16d62a-cdff-11e7-9991-a8b6360436de.png">

**Comment by sunyu912** [comment]
In V1, we also had some Image/Text sections (left-right, right-left). The
problem with that one is that it does not look good once become vertical,
because you will see two images connected vertically. Let's also figure out
a way to bring that kind of Image/Text section to V3.

**Comment by japantaleon** [comment]
Yea I notice, I was thinking we can switch off from the (left-right right-left) depending the course? For the V3, the vertical line graph looked good, but if we where in the robotic course then have the (left-right right-left) would look better. 

Actually, we can input that (left-right right-left) layout into the About part ?

**Comment by sunyu912** [comment]
1. Get the 5 sections to V3 using the template from http://codingmindsacademy.com/page-about-us-1.html 
2. Move the Registration section to the bottom
3. Get the "About the Camp" section to the V3 template. Make sure the mobile view looks nice.
